set_property PACKAGE_PIN P11 [get_ports {zvns[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {zvns[0]}]
set_property PACKAGE_PIN N12 [get_ports {zvns[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {zvns[1]}]
set_property PACKAGE_PIN P13 [get_ports {zvns[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {zvns[2]}]
set_property PACKAGE_PIN M1 [get_ports {zvns[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {zvns[3]}]
