/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteen_bit_multiplier_20 (
    input [15:0] x,
    input [15:0] y,
    output reg [15:0] p
  );
  
  
  
  always @* begin
    p = x * y;
  end
endmodule
